(ns net.wikipunk.rdf.loc.preservation.eventOutcome
  "http://id.loc.gov/vocabulary/preservation/eventOutcome/"
  {:dcat/downloadURL
   "http://id.loc.gov/vocabulary/preservation/eventOutcome.rdf",
   :rdf/ns-prefix-map
   {"bf"      "http://id.loc.gov/ontologies/bibframe/",
    "bflc"    "http://id.loc.gov/ontologies/bflc/",
    "cc"      "http://creativecommons.org/ns#",
    "cs"      "http://purl.org/vocab/changeset/schema#",
    "dcterms" "http://purl.org/dc/terms/",
    "foaf"    "http://xmlns.com/foaf/0.1/",
    "loc.preservation.eventOutcome"
    "http://id.loc.gov/vocabulary/preservation/eventOutcome/",
    "madsrdf" "http://www.loc.gov/mads/rdf/v1#",
    "owl"     "http://www.w3.org/2002/07/owl#",
    "rdf"     "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs"    "http://www.w3.org/2000/01/rdf-schema#",
    "ri"      "http://id.loc.gov/ontologies/RecordInfo#",
    "skos"    "http://www.w3.org/2004/02/skos/core#",
    "xhtml"   "http://www.w3.org/1999/xhtml"},
   :rdf/type :owl/Ontology,
   :rdfa/prefix "loc.preservation.eventOutcome",
   :rdfa/uri "http://id.loc.gov/vocabulary/preservation/eventOutcome/"})

(def fai
  "The event did not succeed in producing the intended result."
  {:db/ident :loc.preservation.eventOutcome/fai,
   :madsrdf/adminMetadata
   {:rdf/type :ri/RecordInfo,
    :ri/recordChangeDate #inst "2018-09-24T04:00:01.000-00:00",
    :ri/recordContentSource :loc.preservation.eventOutcome/dlc,
    :ri/recordStatus "new"},
   :madsrdf/authoritativeLabel "fail",
   :madsrdf/code "fai",
   :madsrdf/definitionNote
   {:rdf/language "en",
    :rdf/value "The event did not succeed in producing the intended result."},
   :madsrdf/isMemberOfMADSCollection
   :loc.preservation.eventOutcome/collection_PREMIS,
   :madsrdf/isMemberOfMADSScheme [:loc.preservation/eventOutcome
                                  :loc.vocabulary/preservation],
   :rdf/type :madsrdf/Authority,
   :skos/changeNote {:cs/changeReason    "new",
                     :cs/createdDate     #inst "2018-09-24T04:00:01.000-00:00",
                     :cs/creatorName     :loc.preservation.eventOutcome/dlc,
                     :cs/subjectOfChange :loc.preservation.eventOutcome/fai,
                     :rdf/type           :cs/ChangeSet},
   :skos/definition
   {:rdf/language "en",
    :rdf/value "The event did not succeed in producing the intended result."},
   :skos/inScheme [:loc.preservation/eventOutcome :loc.vocabulary/preservation],
   :skos/notation "fai",
   :skos/prefLabel "fail"})

(def suc
  "The event succeeded in having its intended result."
  {:db/ident :loc.preservation.eventOutcome/suc,
   :madsrdf/adminMetadata
   {:rdf/type :ri/RecordInfo,
    :ri/recordChangeDate #inst "2018-09-24T04:00:01.000-00:00",
    :ri/recordContentSource :loc.preservation.eventOutcome/dlc,
    :ri/recordStatus "new"},
   :madsrdf/authoritativeLabel "success",
   :madsrdf/code "suc",
   :madsrdf/definitionNote
   {:rdf/language "en",
    :rdf/value    "The event succeeded in having its intended result."},
   :madsrdf/isMemberOfMADSCollection
   :loc.preservation.eventOutcome/collection_PREMIS,
   :madsrdf/isMemberOfMADSScheme [:loc.vocabulary/preservation
                                  :loc.preservation/eventOutcome],
   :rdf/type :madsrdf/Authority,
   :skos/changeNote {:cs/changeReason    "new",
                     :cs/createdDate     #inst "2018-09-24T04:00:01.000-00:00",
                     :cs/creatorName     :loc.preservation.eventOutcome/dlc,
                     :cs/subjectOfChange :loc.preservation.eventOutcome/suc,
                     :rdf/type           :cs/ChangeSet},
   :skos/definition {:rdf/language "en",
                     :rdf/value
                     "The event succeeded in having its intended result."},
   :skos/inScheme [:loc.vocabulary/preservation :loc.preservation/eventOutcome],
   :skos/notation "suc",
   :skos/prefLabel "success"})

(def war
  "A warning was generated by the event, indicating that it needs to be evaluated. Also includes partial success, e.g. a Schematron validation message like \"you should probably include this information if you can\""
  {:db/ident :loc.preservation.eventOutcome/war,
   :madsrdf/adminMetadata
   {:rdf/type :ri/RecordInfo,
    :ri/recordChangeDate #inst "2018-09-24T04:00:01.000-00:00",
    :ri/recordContentSource :loc.preservation.eventOutcome/dlc,
    :ri/recordStatus "new"},
   :madsrdf/authoritativeLabel "warning",
   :madsrdf/code "war",
   :madsrdf/definitionNote
   {:rdf/language "en",
    :rdf/value
    "A warning was generated by the event, indicating that it needs to be evaluated. Also includes partial success, e.g. a Schematron validation message like \"you should probably include this information if you can\""},
   :madsrdf/isMemberOfMADSCollection
   :loc.preservation.eventOutcome/collection_PREMIS,
   :madsrdf/isMemberOfMADSScheme [:loc.vocabulary/preservation
                                  :loc.preservation/eventOutcome],
   :rdf/type :madsrdf/Authority,
   :skos/changeNote {:cs/changeReason    "new",
                     :cs/createdDate     #inst "2018-09-24T04:00:01.000-00:00",
                     :cs/creatorName     :loc.preservation.eventOutcome/dlc,
                     :cs/subjectOfChange :loc.preservation.eventOutcome/war,
                     :rdf/type           :cs/ChangeSet},
   :skos/definition
   {:rdf/language "en",
    :rdf/value
    "A warning was generated by the event, indicating that it needs to be evaluated. Also includes partial success, e.g. a Schematron validation message like \"you should probably include this information if you can\""},
   :skos/inScheme [:loc.vocabulary/preservation :loc.preservation/eventOutcome],
   :skos/notation "war",
   :skos/prefLabel "warning"})

(def ^{:private true} eventOutcome
  "A categorization of the overall result of the Event in terms of success, partial success, or failure."
  {:db/ident :loc.preservation/eventOutcome,
   :madsrdf/adminMetadata {:rdf/type :ri/RecordInfo,
                           :ri/recordChangeDate
                           #inst "2018-09-24T04:00:01.000-00:00",
                           :ri/recordContentSource :loc.preservation/dlc,
                           :ri/recordStatus "new"},
   :madsrdf/hasMADSSchemeMember [:loc.preservation.eventOutcome/fai
                                 :loc.preservation.eventOutcome/suc
                                 :loc.preservation.eventOutcome/war],
   :rdf/type [:skos/ConceptScheme :madsrdf/MADSScheme],
   :rdfs/comment
   "A categorization of the overall result of the Event in terms of success, partial success, or failure.",
   :rdfs/label {:rdf/language "en",
                :rdf/value    "Event Outcome"},
   :skos/changeNote {:cs/changeReason    "new",
                     :cs/createdDate     #inst "2018-09-24T04:00:01.000-00:00",
                     :cs/creatorName     :loc.preservation/dlc,
                     :cs/subjectOfChange :loc.preservation/eventOutcome,
                     :rdf/type           :cs/ChangeSet}})