(ns net.wikipunk.rdf.loc.hubs
  "<xhtml:div xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" class=\"aboutCS\" property=\"rdfs:comment\" title=\"About the Hubs Scheme:\"> <xhtml:p>These Hub descriptions from the Library of Congress Catalog were primarily generated by converting the Library's MARC Bibliographic records and MARC title authority records to BIBFRAME Hub descriptions. This database is a work in progress and the searching capabilities and description displays will be continuously modified and improved.</xhtml:p> <xhtml:p>Hubs may link to other Hubs or Bibframe Works.</xhtml:p> </xhtml:div>"
  {:dcat/downloadURL "https://id.loc.gov/resources/hubs.rdf",
   :madsrdf/adminMetadata {:rdf/type :ri/RecordInfo,
                           :ri/recordChangeDate
                           #inst "2019-06-20T04:00:00.000-00:00",
                           :ri/recordContentSource :loc.organizations/dlcmrc,
                           :ri/recordStatus "modified"},
   :rdf/ns-prefix-map {"bf"       "http://id.loc.gov/ontologies/bibframe/",
                       "cc"       "http://creativecommons.org/ns#",
                       "dcterms"  "http://purl.org/dc/terms/",
                       "foaf"     "http://xmlns.com/foaf/0.1/",
                       "loc.hubs" "http://id.loc.gov/resources/hubs/",
                       "madsrdf"  "http://www.loc.gov/mads/rdf/v1#",
                       "owl"      "http://www.w3.org/2002/07/owl#",
                       "rdf"      "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                       "rdfs"     "http://www.w3.org/2000/01/rdf-schema#",
                       "ri"       "http://id.loc.gov/ontologies/RecordInfo#",
                       "skos"     "http://www.w3.org/2004/02/skos/core#",
                       "xhtml"    "http://www.w3.org/1999/xhtml"},
   :rdf/type :owl/Ontology,
   :rdf/uri "http://id.loc.gov/resources/hubs",
   :rdfa/prefix "loc.hubs",
   :rdfa/uri "http://id.loc.gov/resources/hubs/",
   :rdfs/comment
   "\n      <xhtml:div xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" class=\"aboutCS\" property=\"rdfs:comment\" title=\"About the Hubs Scheme:\">\n                <xhtml:p>These Hub descriptions from the Library of Congress Catalog were primarily \n                generated by converting the Library's MARC Bibliographic records and MARC title authority records to BIBFRAME Hub \n                descriptions. This database is a \n                work in progress and the searching capabilities and description displays will be continuously modified and improved.</xhtml:p>\n                <xhtml:p>Hubs may link to other Hubs or Bibframe Works.</xhtml:p>\n            </xhtml:div>\n    ",
   :rdfs/label {:rdf/language "en",
                :rdf/value    "Library of Congress Hubs"}})